image: "docker.elastic.co/beats/filebeat"
imageTag: "8.0.0-SNAPSHOT"
imagePullPolicy: "IfNotPresent"

nameOverride: "filebeat"
fullnameOverride: "filebeat"

filebeatConfig:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - condition.and:
              - contains:
                  kubernetes.labels.chart: logstash
              config:
                - type: container
                  paths:
                    - /var/log/containers/*-${data.kubernetes.container.id}.log
                  exclude_lines: ["^\\s+[\\-`('.|_]"]

    setup.kibana:
      hosts: "kibana:5601"

    output.kafka:
      hosts: ["kafka:9092"]
      topic: 'ohcore-logs'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        curl --fail 127.0.0.1:5066
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        filebeat test output
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "150m"
    memory: "200Mi"

updateStrategy: RollingUpdate

# tolerations:
# - key: env
#   operator: Equal
#   value: prod
#   effect: NoSchedule
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: env
#           operator: In
#           values:
#           - prod