serviceAccount:
  create: true

image:
  repository: zenko/kafka-manager
  tag: 1.3.3.22
  pullPolicy: IfNotPresent

zkHosts: "kafka-zookeeper:2181"

basicAuth:
  enabled: true
  username: admin
  password: admin

service:
  type: ClusterIP
  port: 9000

resources:
 requests:
   cpu: 200m
   memory: 200Mi
 limits:
   cpu: 250m
   memory: 300Mi

zookeeper:
  enabled: false

# tolerations:
# - key: env
#   operator: Equal
#   value: misc
#   effect: NoSchedule
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: env
#           operator: In
#           values:
#           - misc